/*--------------------------------------*-
文件：	includes.h
时间：2016年3月30日
作者：HWY
版本：V1.0
-*---------------------------------------*/

#ifndef _INCLUDES_H
#define _INCLUDES_H

#include <reg52.h>
#include "config.h"
#include "sch51.h"
#include "t0_uart_init.h"
#include "task.h"

#define uint unsigned int
#define uchar unsigned char

#endif

/*------------------------------------------------------------------*-
-*--------------------     END OF FILE     ---------------------------
-*------------------------------------------------------------------*/